// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jmFd01O-iq5G6uJA7jjE0gkQidw41zc',
    appId: '1:580085759641:web:c953ea66a19eb8f2b5c208',
    messagingSenderId: '580085759641',
    projectId: 'freshloop-18v',
    authDomain: 'freshloop-18v.firebaseapp.com',
    storageBucket: 'freshloop-18v.firebasestorage.app',
    measurementId: 'G-THS18P4YTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkWdK-V1C9ci2QWwtBp_qsuSlB9HuCP8Y',
    appId: '1:580085759641:android:28af413a6ddd458cb5c208',
    messagingSenderId: '580085759641',
    projectId: 'freshloop-18v',
    storageBucket: 'freshloop-18v.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_AC1SvT_LmcABBEwzCa4Mp08WLYHtp8',
    appId: '1:580085759641:ios:bd0e994a0fa3e350b5c208',
    messagingSenderId: '580085759641',
    projectId: 'freshloop-18v',
    storageBucket: 'freshloop-18v.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_AC1SvT_LmcABBEwzCa4Mp08WLYHtp8',
    appId: '1:580085759641:ios:bd0e994a0fa3e350b5c208',
    messagingSenderId: '580085759641',
    projectId: 'freshloop-18v',
    storageBucket: 'freshloop-18v.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jmFd01O-iq5G6uJA7jjE0gkQidw41zc',
    appId: '1:580085759641:web:2fc6d6f7d7fd5e4eb5c208',
    messagingSenderId: '580085759641',
    projectId: 'freshloop-18v',
    authDomain: 'freshloop-18v.firebaseapp.com',
    storageBucket: 'freshloop-18v.firebasestorage.app',
    measurementId: 'G-W92V9197K1',
  );
}
